version: '3.8'

services:
  exam_db:
    image: postgres:15
    container_name: exam_db
    environment:
      POSTGRES_DB: exam_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init_exam_db/init_exam_db.sql:/docker-entrypoint-initdb.d/init.sql
      - exam_data:/var/lib/postgresql/data
    networks:
      - saga_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d exam_db"]
      interval: 10s
      retries: 5

  student_db:
    image: postgres:15
    container_name: student_db
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - student_data:/var/lib/postgresql/data
      - ./sql/init_student_db/init_student_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - saga_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d student_db"]
      interval: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - saga_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      retries: 5

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile.wildfly
    container_name: wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      EXAM_DB_HOST: exam_db
      STUDENT_DB_HOST: student_db
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      SMTP_APP_PASSWORD: ${SMTP_APP_PASSWORD}
    depends_on:
      exam_db:
        condition: service_healthy
      student_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - saga_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9990/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  saga_network:
    driver: bridge

volumes:
  exam_data:
  student_data:
